feat: upload files to storage
dynamicdevs/dynamic-proof pull request #5
Opened 2022-08-04 22:57 UTC by PandaGO13

- Add upload storage function
- Upload, qr mage, pdf and image certification.

2022-08-05 20:21 UTC, c1sar requested changes

2022-08-05 20:21 UTC, c1sar commented on apps/api/src/app/generator/templates/hackaton2022.html
> +      <img src="{{urlBase}}/assets/templates/0001/logo-hackathon2022.png" alt="Logo Hackathon 2022">
Code 001 isn't a variable or const?

2022-08-08 14:22 UTC, PandaGO13 commented on apps/api/src/app/generator/templates/hackaton2022.html
> +      <img src="{{urlBase}}/assets/templates/0001/logo-hackathon2022.png" alt="Logo Hackathon 2022">
Done

2022-08-08 22:29 UTC, c1sar approved these changes

2022-08-08 22:56 UTC, merged